---
title: "hendon_hooker_career"
author: "Heff"
date: "2025-04-30"
output: html_document
---

```{r}
library(tidyverse)
library(cfbfastR)
library(cfbplotR)
library(ggnewscale)
library(showtext)

###############################################################################
```

```{r}
Sys.setenv(CFBD_API_KEY = "VXuXNSm/RT0sJG6nbSnTTNZYHJDjASntcIYw6WpA+Ms+j/lkU7T9/d/i2GIKKVaj")
```

```{r}
add_logo <- function(plot_path, logo_path, logo_position, logo_scale = 10) {
  
  if (!logo_position %in% c("top right", "top left", "bottom right",
                            "bottom left")) {
    stop("Error Message: Uh oh! Logo Position not recognized\n  Try: logo_positon = 'top left', 'top right', 'bottom left', or 'bottom right'")
    
  }
  
  # Read in raw images.
  plot <- magick::image_read(plot_path)
  logo_raw <- magick::image_read(logo_path)
  
  # Get dimensions of plot for scaling.
  plot_height <- magick::image_info(plot)$height
  plot_width <- magick::image_info(plot)$width
  
  # Default scale to 1/10th width of plot.
  # Can change with logo_scale.
  logo <- magick::image_scale(logo_raw, as.character(plot_width / logo_scale))
  
  # Get width of logo.
  logo_width <- magick::image_info(logo)$width
  logo_height <- magick::image_info(logo)$height
  
  # Set position of logo.
  # Position starts at top left (0, 0).
  # Using 0.01 for 1% - aesthetic padding.
  
  if (logo_position == "top right") {
    x_pos = plot_width - logo_width - 0.08 * plot_width
    y_pos = 0.01 * plot_height
  } else if (logo_position == "top left") {
    x_pos = 0.01 * plot_width
    y_pos = 0.01 * plot_height
  } else if (logo_position == "bottom right") {
    x_pos = plot_width - logo_width - 0.01 * plot_width
    y_pos = plot_height - logo_height - 0.85 * plot_height
  } else if (logo_position == "bottom left") {
    x_pos = 0.01 * plot_width
    y_pos = plot_height - logo_height - 0.01 * plot_height
  }
  
  # Compose the actual overlay.
  magick::image_composite(plot, logo, offset = paste0("+", x_pos, "+", y_pos))
  
}

###############################################################################
```

```{r}
# ── team & player info ──
team_info   <- cfbd_team_info(year = 2022, only_fbs = TRUE) %>%
  filter(school == "Tennessee")
player_info <- cfbd_team_roster(year = 2022, team = "Tennessee") %>%
  filter(firstName == "Hendon")

tenn_col  <- team_info$color
vt_col    <- "#630031"    # Virginia Tech
tenn_logo <- team_info$logo
headshot  <- player_info$headshot_url

# ── load pbp and label QB plays ──
pbp <- load_cfb_pbp(seasons = 2019:2022)

pbp_r <- pbp %>%
  filter(rush == 1) %>%
  mutate(passer_name = rusher_player_name)

pbp_p <- pbp %>%
  filter(pass == 1) %>%
  mutate(passer_name = passer_player_name)

# ── build hooker summary (only Hooker gets in BEFORE summarise) ──
hooker <- bind_rows(pbp_r, pbp_p) %>%
  arrange(game_id, week, game_play_number) %>%
  filter(
    !is.na(EPA),
    is.na(penalty_detail),
    passer_name == "Hendon Hooker"
  ) %>%
  group_by(pos_team, season, week, def_pos_team) %>%
  summarise(
    epa = round(mean(EPA), 2),
    .groups = "drop"
  ) %>%
  mutate(
    text_col = ifelse(epa >= -1.7 & epa <= 0.3, "black", "white")
  ) %>%
  arrange(season, week) %>%
  # patch that one Purdue week
  mutate(
    week = if_else(
      season == 2021 &
      pos_team == "Tennessee" &
      week == 1 &
      def_pos_team == "Purdue" &
      epa == 0.22,
      15L,
      week
    )
  )

# ── optional splits & check ──
hooker_tenn <- hooker %>% filter(pos_team == "Tennessee")
hooker_vt   <- hooker %>% filter(pos_team == "Virginia Tech")

hooker %>% count(season, pos_team)
```


```{r}
font_add_google("Fjalla One", "Fjalla One")
showtext_auto(enable = TRUE)
showtext_opts(dpi = 300)

base <- ggplot(mapping = aes(x = week, y = season)) +
  theme(plot.background = element_rect(fill = "#F0F8FF", colour = "#F0F8FF"),
        panel.background = element_rect(fill = "#F0F8FF"),
        panel.grid = element_blank()) +
  labs(title = "Hendon Hooker's College Career",
       subtitle = "2019-2022 | 2018 redshirt year excluded",
       caption = "Data: @CFB_Data with cfbfastR | Plot: @cover2figuRes | Inspired by @BrunoHMioto",
       x = "Week",
       y = "Season") +
  theme(text = element_text(family = "Fjalla One"),
        plot.title = element_text(size = 20, hjust = 0.5),
        plot.subtitle = element_text(size = 16, hjust = 0.5),
        axis.title = element_text(size = 14),
        plot.caption = element_text(size = 10, hjust = 0.5, vjust = -10)) +
  scale_x_continuous(breaks = seq(1, 15, 1),
                     labels = c(1:14, "Post")) +
  geom_tile(data = hooker_vt,
            aes(fill = epa),
            colour = "white", size = 0.5, show.legend = FALSE) +
  coord_equal() +
  scale_fill_gradientn(colours = c("grey", "white", vt_col),
                       limits = c(-1, 1)) +
  new_scale_fill() +
  geom_tile(data = hooker_tenn,
            aes(fill = epa),
            colour = "white", size = 0.5) +
  scale_fill_gradientn("EPA per Play",
                       colours = c("grey", "white", tenn_col),
                       limits = c(-1, 1),
                       breaks = seq(-1, 1, 0.5)) +
  theme(legend.background = element_rect(fill = "#F0F8FF"),
        legend.position = "top",
        legend.key.width = unit(2, "cm")) +
  guides(fill = guide_colorbar(title.position = "top",
                               title.hjust = 0.5)) +
  geom_cfb_logos(data = hooker,
                 aes(x = week, y = season + 0.2, team = def_pos_team),
                 width = 0.03) +
  geom_text(data = hooker,
            aes(x = week, y = season - 0.2, label = epa, colour = text_col),
            size = 4.5, family = "Fjalla One", show.legend = FALSE) +
  scale_colour_identity() +
  theme(plot.margin = unit(c(1, 1, 3, 1), "lines"))

ragg::agg_png("Base.png", width = 11.7, height = 6,
              units = "in", res = 300)
base
dev.off()

base_img <- magick::image_read("Base.png")

base_raster <- grid::rasterGrob(base_img, width = unit(1, "npc"),
                                height = unit(1, "npc"))

plot_with_personal <- add_logo(
  plot_path = "Base.png",
  logo_path = "Cover2.png",
  logo_position = "bottom left",
  logo_scale = 20
)

magick::image_write(plot_with_personal, "Personal.png")

plot_with_logo <- add_logo(
  plot_path = "Personal.png",
  logo_path = tenn_logo,
  logo_position = "top right",
  logo_scale = 10
)

magick::image_write(plot_with_logo, "Logo.png")

plot_with_headshot <- add_logo(
  plot_path = "Logo.png",
  logo_path = headshot,
  logo_position = "bottom right",
  logo_scale = 8
)

magick::image_write(plot_with_headshot, "Headshot.png")

plot_with_ncaa <- add_logo(
  plot_path = "Headshot.png",
  logo_path = "NCAA.png",
  logo_position = "top left",
  logo_scale = 15
)

magick::image_write(
  plot_with_ncaa,
  path = "/Users/heff/Desktop/jheffernan/cover2figures_tutorials/hendon_hooker_career/hendon_hooker_career.png"
)
```


